version: '3'

volumes:
  shared_tmp:

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - snowcap_network

  app: # uvicorn fastapi python app 
    build: .
    volumes:
      - ./app:/app
      - shared_tmp:/tmp
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - redis
    networks:
      - snowcap_network
    restart: always

  worker:
    build: .
    command: celery -A celery_tasks.tasks worker --loglevel=info
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
      - shared_tmp:/tmp
    depends_on:
      - redis
    networks:
      - snowcap_network
    restart: always
    
  nginx:
    image: nginx:latest
    volumes:
      - ssl_certs:/etc/letsencrypt
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - snowcap_network
      
networks:
  snowcap_network:
    driver: bridge